/**
 * doctor/checks/mcp.ts -- MCP client wiring diagnostic checks.
 *
 * Five checks verifying that MCP clients are present, the ALTER server
 * entry is wired into each, the @truealter/sdk bridge dependency is
 * resolvable, an optional Org Alter MCP target is reachable, and the
 * bridge can complete an initialize handshake.
 *
 * All checks are LOCAL (no phone-home). The live probe (mcp.bridge-handshake)
 * spawns the bridge binary with a bounded timeout and writes an MCP JSON-RPC
 * initialize frame to its stdin. No session data or credentials are
 * transmitted in the probe; the request is intentionally unauthenticated.
 *
 * Policy: diagnose-first; --fix opt-in only.
 * Cryptographic keys are never regenerated by doctor.
 *
 * Reads MCP host config and the bundled bridge dependency.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { spawn, exec, execFile } from "node:child_process";

import {
  defaultMcpHosts,
  probeMcpHosts,
  resolveOrgAlterBin,
  type McpHostFile,
} from "../../lib/mcp-config.js";

/** Result shape mirroring the spawnSync contract the call sites consume:
 *  `.error` is set ONLY for spawn failure / timeout-kill - a non-zero exit
 *  still carries usable stdout/stderr. */
interface ClaudeMcpListProbe {
  error: Error | null;
  stdout: string;
  stderr: string;
}

/**
 * Probe `claude mcp list`.
 *
 * ASYNC on purpose: the prior spawnSync blocked the Node event loop for the
 * full run of `claude mcp list` (seconds), which froze the doctor progress
 * line, defeated the per-check async timeout, and buffered keypresses that
 * later double-fired "press enter to return". exec/execFile keep the loop
 * free so the doctor stays paintable and cancellable.
 *
 * On Windows the `claude` shim is a `.cmd`/`.ps1` wrapper, which Node
 * refuses to spawn directly (EINVAL, CVE-2024-27980 hardening) - a shell
 * is required, so the shell path passes ONE fixed literal command string.
 * No user input is interpolated - the command is a constant - so there is
 * no injection surface.
 */
function probeClaudeMcpList(): Promise<ClaudeMcpListProbe> {
  return new Promise((resolve) => {
    const onDone = (
      error: (Error & { code?: unknown; killed?: boolean }) | null,
      stdout: string,
      stderr: string,
    ): void => {
      // Mirror spawnSync semantics: `.error` only for spawn failure
      // (binary missing) or the timeout kill - a non-zero exit with
      // output is still inspectable.
      const spawnFailure =
        error && (error.code === "ENOENT" || error.killed === true)
          ? error
          : null;
      resolve({ error: spawnFailure, stdout: stdout ?? "", stderr: stderr ?? "" });
    };
    if (process.platform === "win32") {
      exec("claude mcp list", { encoding: "utf8", timeout: 5000 }, onDone);
    } else {
      execFile("claude", ["mcp", "list"], { encoding: "utf8", timeout: 5000 }, onDone);
    }
  });
}
import { wire } from "../../commands/wire.js";

import type {
  Check,
  CheckResult,
  HealResult,
  DoctorCtx,
} from "../../lib/check-report.js";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** True if the file or directory exists. */
function fsExists(p: string): boolean {
  try {
    fs.statSync(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * Read and parse a JSON file. Returns null if the file is absent;
 * throws on permission errors or JSON parse failures.
 */
function readJsonFile(filePath: string): Record<string, unknown> | null {
  let raw: string;
  try {
    raw = fs.readFileSync(filePath, "utf-8");
  } catch (err) {
    const e = err as NodeJS.ErrnoException;
    if (e.code === "ENOENT") return null;
    throw err;
  }
  return JSON.parse(raw) as Record<string, unknown>;
}

/**
 * Check whether the ALTER server entry (key "alter") is present
 * under a given root key in a JSON config file.
 *
 * Returns:
 *   "present"  -- rootKey exists and contains an "alter" sub-key
 *   "absent"   -- file or rootKey absent, or "alter" key missing
 *   "error"    -- file cannot be read / is not valid JSON
 */
function alterEntryStatus(
  configPath: string,
  rootKey: string,
): "present" | "absent" | "error" {
  let obj: Record<string, unknown> | null;
  try {
    obj = readJsonFile(configPath);
  } catch {
    return "error";
  }
  if (obj === null) return "absent";
  const root = obj[rootKey];
  if (root === null || typeof root !== "object" || Array.isArray(root)) {
    return "absent";
  }
  return "alter" in (root as object) ? "present" : "absent";
}

// ---------------------------------------------------------------------------
// mcp.client-present
// ---------------------------------------------------------------------------

const clientPresent: Check = {
  id: "mcp.client-present",
  category: "mcp",
  label: "at least one MCP client detected (Claude Code, Cursor, Desktop, VS Code)",
  healClass: "DIAGNOSE-ONLY",
  live: true,
  async run(_ctx: DoctorCtx): Promise<CheckResult> {
    const probes = probeMcpHosts();
    const detected = probes.filter((p) => p.installed);
    if (detected.length === 0) {
      return {
        status: "WARN",
        detail: "no MCP client directories found",
        remedy:
          "install Claude Code, Cursor, Claude Desktop, or VS Code, then run `alter wire`",
      };
    }
    const labels = detected.map((p) => p.host.label).join(", ");
    return {
      status: "OK",
      detail: `${detected.length} client${detected.length === 1 ? "" : "s"}: ${labels}`,
    };
  },
};

// ---------------------------------------------------------------------------
// mcp.alter-entry
// ---------------------------------------------------------------------------

const alterEntry: Check = {
  id: "mcp.alter-entry",
  category: "mcp",
  label: "~Alter server entry wired into every detected MCP client config",
  healClass: "SAFE-AUTOHEAL",
  live: true,
  async run(_ctx: DoctorCtx): Promise<CheckResult> {
    const probes = probeMcpHosts();
    const installed = probes.filter((p) => p.installed);
    if (installed.length === 0) {
      return {
        status: "WARN",
        detail: "no clients detected -- skipping entry check (see mcp.client-present)",
      };
    }

    const missing: string[] = [];
    const errors: string[] = [];

    for (const p of installed) {
      if (p.host.id === "claude-code") {
        // Claude Code entry is managed via `claude mcp add` (CLI), not a JSON
        // file. Probe: run `claude mcp list` and look for "alter".
        try {
          const result = await probeClaudeMcpList();
          if (result.error) {
            // claude binary missing -- mcp.client-present covers this;
            // treat as unknown here.
            continue;
          }
          const out = (result.stdout ?? "") + (result.stderr ?? "");
          if (!out.includes("alter")) {
            missing.push(p.host.label);
          }
        } catch {
          // Probe failed; don't double-report.
        }
        continue;
      }

      // JSON-file clients (cursor, claude-desktop, vscode).
      const h = p.host as McpHostFile;
      const status = alterEntryStatus(h.configPath, h.rootKey);
      if (status === "absent") {
        missing.push(h.label);
      } else if (status === "error") {
        errors.push(`${h.label}: ${h.configPath} could not be read or parsed`);
      }
    }

    if (errors.length > 0) {
      return {
        status: "WARN",
        detail: errors.join("; "),
        remedy: "check file permissions or hand-fix the JSON, then re-run `alter wire`",
      };
    }
    if (missing.length > 0) {
      return {
        status: "FAIL",
        detail: `Alter entry missing from: ${missing.join(", ")}`,
        remedy:
          "run `alter doctor --fix` to auto-wire, or run `alter wire` manually",
      };
    }
    return {
      status: "OK",
      detail: `Alter entry present in all ${installed.length} detected client${installed.length === 1 ? "" : "s"}`,
    };
  },

  async heal(_ctx: DoctorCtx): Promise<HealResult> {
    // Re-run probe to find only the clients missing the entry.
    const probes = probeMcpHosts();
    const installed = probes.filter((p) => p.installed);
    const missingIds: string[] = [];

    for (const p of installed) {
      if (p.host.id === "claude-code") {
        try {
          const result = await probeClaudeMcpList();
          if (!result.error) {
            const out = (result.stdout ?? "") + (result.stderr ?? "");
            if (!out.includes("alter")) missingIds.push(p.host.id);
          }
        } catch {
          // Leave claude-code out of the targeted list; wire() without --only
          // will cover it.
        }
        continue;
      }
      const h = p.host as McpHostFile;
      if (alterEntryStatus(h.configPath, h.rootKey) === "absent") {
        missingIds.push(h.id);
      }
    }

    if (missingIds.length === 0) {
      return { applied: false, status: "OK", detail: "no missing entries -- nothing to fix" };
    }

    // Delegate to the real wire surface. Pass --only for the affected clients,
    // --yes to skip the interactive prompt, so it runs non-interactively.
    try {
      await wire(["--only", missingIds.join(","), "--yes"]);
      return {
        applied: true,
        status: "OK",
        detail: `ran \`alter wire --only ${missingIds.join(",")}\``,
      };
    } catch (err) {
      return {
        applied: false,
        status: "FAIL",
        detail: `wire failed: ${(err as Error).message}`,
      };
    }
  },
};

// ---------------------------------------------------------------------------
// mcp.sdk-installed
// ---------------------------------------------------------------------------

const sdkInstalled: Check = {
  id: "mcp.sdk-installed",
  category: "mcp",
  label: "@truealter/sdk resolvable (required by mcp-bridge)",
  healClass: "DIAGNOSE-ONLY",
  async run(_ctx: DoctorCtx): Promise<CheckResult> {
    // mcp-bridge.ts resolves @truealter/sdk via createRequire(import.meta.url).
    // Mirror that resolution here.
    const require = createRequire(import.meta.url);
    try {
      const resolved = require.resolve("@truealter/sdk");
      if (!fsExists(resolved)) {
        return {
          status: "FAIL",
          detail: `@truealter/sdk resolved to ${resolved} but file is absent`,
          remedy: "reinstall: npm install @truealter/sdk",
        };
      }
      return { status: "OK", detail: resolved };
    } catch {
      return {
        status: "FAIL",
        detail: "@truealter/sdk not resolvable from the CLI package root",
        remedy:
          "reinstall the CLI or run: npm install @truealter/sdk",
      };
    }
  },
};

// ---------------------------------------------------------------------------
// mcp.collective-binary
// ---------------------------------------------------------------------------

const collectiveBinary: Check = {
  id: "mcp.collective-binary",
  category: "mcp",
  label: "Org Alter MCP reachable",
  healClass: "DIAGNOSE-ONLY",
  async run(_ctx: DoctorCtx): Promise<CheckResult> {
    let bin: import("../../lib/mcp-config.js").OrgAlterBin;
    try {
      // resolveOrgAlterBin walks up from import.meta.url.
      // For the check, pass the check module's own URL as start so it
      // walks from the same root the CLI itself would.
      const here = path.dirname(fileURLToPath(import.meta.url));
      bin = resolveOrgAlterBin(here);
    } catch {
      // Resolution failed. Org Alter MCP is optional and not present on
      // most machines; treat a resolver miss as "not configured", with no
      // wiring instructions, rather than a fault.
      return {
        status: "OK",
        detail: "Org Alter MCP not configured (optional)",
      };
    }

    if (bin.kind === "unavailable") {
      // Org Alter MCP is optional and not present here. Informational, not
      // a failure: a CLI install is not expected to carry it.
      return {
        status: "OK",
        detail: "Org Alter MCP not configured (optional)",
      };
    }

    // Reachable target resolved and trust-verified by resolveOrgAlterBin.
    if (!fsExists(bin.path)) {
      return {
        status: "OK",
        detail: "Org Alter MCP not configured (optional)",
      };
    }
    return { status: "OK", detail: "Org Alter MCP reachable" };
  },
};

// ---------------------------------------------------------------------------
// mcp.bridge-handshake (live probe)
// ---------------------------------------------------------------------------

/**
 * Locate the mcp-bridge.js file the same way mcp-bridge.ts does:
 * resolve @truealter/sdk then look for mcp-bridge.js in the dist tree.
 * Returns null if not found (i.e. sdk not installed).
 */
function findBridgePath(): string | null {
  const require = createRequire(import.meta.url);
  try {
    const sdkEntry = require.resolve("@truealter/sdk");
    const sdkDir = path.dirname(sdkEntry);
    const candidate = path.resolve(sdkDir, "mcp-bridge.js");
    if (fsExists(candidate)) return candidate;
    const binCandidate = path.resolve(sdkDir, "bin", "mcp-bridge.js");
    if (fsExists(binCandidate)) return binCandidate;
  } catch {
    // sdk not resolvable
  }
  // Sibling dist path (dev checkout).
  const here = path.dirname(fileURLToPath(import.meta.url));
  const localCandidate = path.resolve(
    here,
    "..",
    "..",
    "node_modules",
    "@truealter",
    "sdk",
    "dist",
    "mcp-bridge.js",
  );
  if (fsExists(localCandidate)) return localCandidate;
  return null;
}

const bridgeHandshake: Check = {
  id: "mcp.bridge-handshake",
  category: "mcp",
  label: "MCP bridge responds to initialize handshake",
  healClass: "DIAGNOSE-ONLY",
  live: true,
  async run(ctx: DoctorCtx): Promise<CheckResult> {
    const bridgePath = findBridgePath();
    if (!bridgePath) {
      return {
        status: "WARN",
        detail: "bridge script not found (mcp.sdk-installed may also be failing)",
        remedy: "reinstall @truealter/sdk",
      };
    }

    const timeout = Math.min(ctx.timeoutMs, 3000);

    return new Promise<CheckResult>((resolve) => {
      let settled = false;
      let stdout = "";
      let timedOut = false;

      const timer = setTimeout(() => {
        timedOut = true;
        if (!settled) {
          settled = true;
          child.kill("SIGTERM");
          resolve({
            status: "WARN",
            detail: `bridge did not respond within ${timeout}ms`,
            remedy:
              "check network connectivity to mcp.truealter.com, or run `alter mcp-bridge` to inspect output",
          });
        }
      }, timeout);

      const child = spawn(process.execPath, [bridgePath], {
        stdio: ["pipe", "pipe", "pipe"],
        env: { ...process.env },
      });

      child.on("error", (err) => {
        clearTimeout(timer);
        if (!settled) {
          settled = true;
          resolve({
            status: "WARN",
            detail: `bridge spawn error: ${err.message}`,
            remedy: "reinstall @truealter/sdk",
          });
        }
      });

      child.stdout?.on("data", (chunk: Buffer) => {
        stdout += chunk.toString("utf-8");
        // Look for a valid JSON-RPC response line.
        const lines = stdout.split("\n");
        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed) continue;
          try {
            const msg = JSON.parse(trimmed) as Record<string, unknown>;
            if (msg.jsonrpc === "2.0" && "result" in msg) {
              clearTimeout(timer);
              if (!settled) {
                settled = true;
                child.kill("SIGTERM");
                resolve({ status: "OK", detail: "bridge returned initialize result" });
              }
              return;
            }
          } catch {
            // not a complete JSON line yet -- accumulate
          }
        }
      });

      child.on("exit", (code) => {
        clearTimeout(timer);
        if (!settled) {
          settled = true;
          if (timedOut) return; // already resolved
          resolve({
            status: "WARN",
            detail: `bridge exited (${String(code)}) before responding`,
            remedy:
              "run `alter mcp-bridge` to inspect stderr output",
          });
        }
      });

      // Send an MCP initialize request to the bridge's stdin.
      // The request is intentionally unauthenticated -- we only probe that
      // the bridge binary starts and speaks JSON-RPC correctly.
      const initRequest = JSON.stringify({
        jsonrpc: "2.0",
        id: 1,
        method: "initialize",
        params: {
          protocolVersion: "2024-11-05",
          capabilities: {},
          clientInfo: { name: "alter-doctor", version: "0" },
        },
      }) + "\n";

      try {
        child.stdin?.write(initRequest);
        child.stdin?.end();
      } catch {
        // If stdin write fails, the exit handler will resolve.
      }
    });
  },
};

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

export const checks: Check[] = [
  clientPresent,
  alterEntry,
  sdkInstalled,
  collectiveBinary,
  bridgeHandshake,
];
